evmmarket/ecomapp/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from ecomapp.views import (
    base_view,
    category_view,
    product_view,
    cart_view,
    add_to_cart_view,
    remove_from_cart_view,
    change_item_qty,
    checkout_view,
    order_create_view,
    make_order_view,
    account_view )


urlpatterns =[
    url(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
    url(r'^cart/$', cart_view, name ='cart'),
    url(r'^add_to_cart/$', add_to_cart_view, name='add_to_cart'),
    url(r'^remove_from_cart/$', remove_from_cart_view, name='remove_from_cart'),
    url(r'^change_item_qty/$', change_item_qty, name='change_item_qty'),
    url(r'^checkout/$', checkout_view, name='checkout'),
    url(r"^order/$", order_create_view, name='create_order'),
    url(r'^make_order/$', make_order_view, name='make_order'),
    url(r'^thank_you/$', TemplateView.as_view(template_name='thank_you.html'), name='thank_you'),
    url(r'^account/$', account_view, name='account'),
    url(r'^$', base_view, name='base'),
]

evmmarket/evmmarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('ecomapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

evmmarket/ecomapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from transliterate import translit
from django.db.models.signals import pre_save
from django.utils.text import slugify   # для перевода поля slug на латиницу
from django.urls import reverse
from decimal import Decimal

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(blank=True)   # ссылка у каждой КАТЕГОРИИ

    def __str__(self):
        return self.name    # нормальное отображение категорий в АДМИНКЕ

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug':self.slug})


def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.name), reversed=True))
        instance.slug = slug    # транслитерация SLUG на латиницу


pre_save.connect(pre_save_category_slug, sender=Category)


class Brands(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


def images_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)    # формирование ссылки на img


# переопределяем базовый менеджер, чтобы можно было деактивировать товар с сайта

class ProductManager(models.Manager):

    def all(self, *args, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    brand = models.ForeignKey(Brands, on_delete=models.PROTECT)
    title = models.CharField(max_length=150)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=images_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    available = models.BooleanField(default=True)
    objects = ProductManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug':self.slug})


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return "Cart item to product  {0}".format(self.product.title)


class Cart(models.Model):
    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self,product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()

    def remove_from_cart(self,product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()


    def change_qty(self,qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.items.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()



ORDER_STATUS_CHOICES = (
    ('прПринят в обработку', 'Принят в обработку'),
    ('Выполняется', 'Выполняется'),
    ('Оплачен', 'Оплачен')
)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)
    items = models.ManyToManyField(Cart)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=25)
    address = models.CharField(max_length=150)
    buying_type = models.CharField(max_length=40, choices=(('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')), default='Самовывоз')
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES)

    def __str__(self):
        return "Заказ №{0}".format(str(self.id))

evmmarket/ecomapp/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils import timezone


class OrderForm(forms.Form):
    name = forms.CharField()
    last_name = forms.CharField(required=False)
    phone = forms.CharField()
    buying_type = forms.ChoiceField(widget=forms.Select(), choices=(('self', 'Самовывоз'), ('delivery', 'Доставка')))
    date = forms.DateField(widget=forms.SelectDateWidget(), initial=timezone.now())
    address = forms.CharField(required=False)
    comments = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Имя'
        self.fields['last_name'].label = 'фамилия'
        self.fields['phone'].label = 'Телефон'
        self.fields['phone'].help_text = 'Пожалуйста, укажите реальный номер телефона по которому свяжется менеджер'
        self.fields['buying_type'].label = 'Способ получения'
        self.fields['address'].help_text ='Обязательно указывайте город!'
        self.fields['comments'].label ='Комментарии к заказу'
        self.fields['date'].label = 'Дата доставки'
        self.fields['date'].help_text = 'Доставка производится на следующий день после оформления заказа'

evmmarket/ecomapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from decimal import Decimal
from django import forms
from ecomapp.models import Category, Product, CartItem, Cart, Order
from ecomapp.forms import OrderForm
# Create your views here.


def base_view(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    return render(request, 'base.html', context={'categories': categories, 'products': products, 'cart': cart})


# вьюхи для создания ссылок на Категории и Продукты
def product_view(request, product_slug):
    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    return render(request, 'product.html', context={'product': product,'categories': categories, 'cart': cart})


def category_view(request, category_slug):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    category = Category.objects.get(slug=category_slug)
    products_of_category = Product.objects.filter(category=category)
    return render(request, 'category.html', context={'category': category, 'products_of_category': products_of_category, 'categories': categories,})


# Корзина
def cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
        product_slug = request.GET.get('product_slug')
        product = Product.objects.get(slug=product_slug)
        cart.add_to_cart(product.slug)
    categories = Category.objects.all()
    return render(request, 'cart.html', context={'cart': cart, 'categories': categories})


# Добавление товара в корзину
def add_to_cart_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.add_to_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total' : cart.items.count(), 'cart_total_price': cart.cart_total})


def remove_from_cart_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})


def change_item_qty(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart.change_qty(qty, item_id)
    cart_item = CartItem.objects.get(id=int(item_id))
    return JsonResponse(
        {"cart_total": cart.items.count(),
         'item_total': cart_item.item_total,
         'cart_total_price': cart.cart_total
         })


def checkout_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    return render(request, 'checkout.html', context={'cart': cart})


def order_create_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    categories = Category.objects.all()
    return render(request, 'order.html', context={'form': form, 'cart': cart, 'categories': categories})


def make_order_view(request):

    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    categories = Category.objects.all()
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        comments = form.cleaned_data['comments']
        new_order = Order()
        new_order.user = request.user
        new_order.save()
        new_order.items.add(cart)
        new_order.first_name = name
        new_order.last_name = last_name
        new_order.phone = phone
        new_order.buying_type = buying_type
        new_order.address = address
        new_order.comments = comments
        new_order.total = cart.cart_total
        new_order.save()
        del request.session['cart_id']
        del request.session['total']
        return HttpResponseRedirect(reverse('thank_you'))
    return render(request, 'order.html', context={'categories': categories})


def account_view(request):
    order = Order.objects.filter(user=request.user)
    return render(request, 'account.html', context={'order': order})

evmmarket/ecomapp/templates/account.html
{% extends 'base.html' %}

{% block content %}

<h3 class="text-center">Личный кабинет {{ request.user }}</h3>
<hr>
<h4 class="text-center">Ваши заказы</h4>
<table class="table">
    {% for item in order %}
    <tr style="background: lightblue">
        <td>Номер заказа</td>
        <td>Дата заказа</td>
        <td>Статус заказа</td>
        <td>Стоимость заказа</td>
        <td>Детали заказа</td>
    </tr>
    <tr>
        <td>{{ item.id}}</td>
        <td>{{ item.date }}</td>
        <td>{{ item.status }}</td>
        <td>{{ item.total}}</td>
        <td></td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

evmmarket/ecomapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>EVM</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop-homepage.css' %}">
    <script src='{% static "js/jquery.js" %}'></script>
</head>
<body>
    <body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">EVM- маркет</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <!-- условие скрывает навигацию на главной странице -->
    {% if not request.get_full_path == '/' %}
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Категории<li>
        </li>
        </a>
        <div class="dropdown-menu">
          {% for category in categories %}
            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
          {% endfor %}
        </div>
  </li>
            {% endif %}
            {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="#">Гость</a>
          </li>
            {% else %}
           <li class="nav-item">
               <a class="nav-link" href="{% url 'account' %}">{{ request.user }} </a>
           </li>
            {% endif %}
        <li>
            <a class="nav-link" href="/">Домой
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">О нас</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge" id="cart_count">{% if not request.session.total %}
            0 {% else %} {{ request.session.total }} {% endif %} </span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <br>
  <!-- Page Content -->
  <div class="container">
        {% block content %}
    <div class="row">

      <div class="col-lg-3">

      </div>
      <!-- /.col-lg-3 -->
      <div class="col-lg-9">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="http://placehold.it/900x350" alt="Первый слайд">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="http://placehold.it/900x350" alt="Второй слайд">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="http://placehold.it/900x350" alt="Третий слайд">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
          <br>
        <div class="row">
            {% for product in products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <img src="{{ product.image.url }}" alt="товар" style="width: 100%", height="250px" ></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}" style="color: #000; font-weight: bold;">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }} руб.</h5>
                {% if request.user.is_authenticated %}<p class="text-right"><a href="#" class="add_to_cart" data-slug="{{ product.slug }}">
                  <button class="btn btn-danger">В корзину</button></a></p>
                  {% else %}
                  {% endif %}
              </div>
            </div>
          </div>
            {% endfor %}
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->
      {% endblock content %}
  </div>

  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "js/bootstrap.js" %}'></script>

  <script>
      $(document).ready(function () {
          $('.add_to_cart').on('click', function (e) {
              e.preventDefault()
              product_slug = $(this).attr('data-slug')
              data = {
                  product_slug: product_slug
              }
              $.ajax({
                  type: "GET",
                  url: '{% url "add_to_cart" %}',
                  data: data,
                  success: function (data) {
                      $("#cart_count").html(data.cart_total)
                  }
              })
          })
      })
  </script>
</body>

</body>
</html>

evmmarket/ecomapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center">Ваша корзина</h3>
<br>
{% if cart.items.count > 0 %}
<div class="my_cart">


<table class="table">
    <tr>
    <td class="text-center">Товар</td>
    <td class="text-center">Количество</td>
    <td class="text-center">Цена: </td>
    </tr>

    {% for item in cart.items.all %}
  <tr id="{{ item.product.slug }}" ">
      <input type="hidden" class="cart-item" data-id="{{ item.product.id }}">
    <td class="text-center">{{item.product.title}}</td>
    <td class="text-center">
        <form action="" method="GET">
            <input type="number" name="qty" class="cart-item-qty" data-id="{{ item.id }}" value="{{ item.qty }}" min="1" style="width: 40px;">
        </form>
    </td>
    <td class="text-center" id="cart-item-total-{{ item.id }}">{{item.item_total}} руб.</td>
    <td class="text-center"><a href='#' class="remove_from_cart" data-slug="{{ item.product.slug }}"><button class="btn btn-danger">Удалить из корзины</button></a></td>
  </tr>
    {% endfor %}
    <tr>
        <td></td>
        <td class="text-center">Итого:</td>
        <td class="text-center" id="cart-total-price"><strong>{{ cart.cart_total }} руб.</strong></td>
        <td class="text-center"></td>
    </tr>
</table>
    <br>
    <a href="{% url 'checkout' %}" class="pull-right"><button class="btn btn-info">Мой заказ</button></a>
</div>
    <h3 class="cart-empty"></h3>
    {% else %}
    <h3 class="text-center">Ваша корзина пуста</h3>
    {% endif %}
    <script>

    $(document).ready(function () {
        $('.remove_from_cart').on('click', function f(e) {
            e.preventDefault()
            product_slug = $(this).attr('data-slug')
            item_product_id =$('.cart-item').attr('data-id')
            data = {
                product_slug: product_slug
            }
            $.ajax({
                type: "GET",
                url: '{% url "remove_from_cart" %}',
                data: data,
                success: function (data) {
                    $("#cart_count").html(data.cart_total)
                    $('#'+product_slug).remove()
                    $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2)+ 'руб. </strong>')
                }
            })
        })
    })
        $(document).ready(function () {
            $('.cart-empty').css('display', 'none')
            $('.cart-item-qty').on('click', function () {
                qty =$(this).val()
                item_id = $(this).attr('data-id')
                console.log(item_id)
                data = {
                    qty: qty,
                    item_id: item_id
                }
                $.ajax({
                    type: 'GET',
                    url: '{% url "change_item_qty" %}',
                    data: data,
                    success: function (data) {
                        $('#cart-item-total-'+ item_id).html(parseFloat(data.item_total).toFixed(2) + ' руб.')
                        $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2)+ 'руб. </strong>')
                        if(parseInt(data.cart_total) == 0){
                            $('.my_cart').remove()
                            $('.cart-empty').css('display', 'block')
                            $('.cart-empty').html('<h3 class="text-center">Ваша корзина пуста</h3>')
                        }
                    }
                })
            })
        })
    </script>
</table>

{% endblock content %}

evmmarket/ecomapp/templates/category.html
{% extends 'base.html' %}

{% block content %}

    <div class="col-sm-12">
        <h2 class="text-center">{{ category.name }}</h2>
        <p>{{ product.title }}</p>
        <hr>
    </div>
<div class="container">
    <div class="row">
    {% for product in products_of_category %}

    <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <img class="card-img-top" src="{{ product.image.url }}" alt="продукт">
                <p class="text-center"><a href="{{ product.get_absolute_url }}" class="card-title" style="color: #000; font-weight: bold;">{{ product.title}}</a></p>
                <p class="text-center" style="font-size: 20px; font-weight: bold;">{{ product.price }} руб.</p>
                   {% if request.user.is_authenticated %} <a href="#" class="add_to_cart" data-slug='{{ product.slug}}'>
                    <button class="btn btn-danger">Добавить в корзину</button></a>
                    {% else %}
                    <p class="text-center">Для заказа <a href="#">Войдите</a> или <a href="#">Зарегистрируйтесь</a></p>
                    {% endif %}
            </div>
        </div>
    </div>
<br>
    {% endfor %}

          <script>
      $(document).ready(function () {
          $('.add_to_cart').on('click', function (e) {
              e.preventDefault()
              product_slug = $(this).attr('data-slug')
              data = {
                  product_slug: product_slug
              }
              $.ajax({
                  type: "GET",
                  url: '{% url "add_to_cart" %}',
                  data: data,
                  success: function (data) {
                      $("#cart_count").html(data.cart_total)
                  }
              })
          })
      })
  </script>
       </div>
    </div>

{% endblock content %}

evmmarket/ecomapp/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<form action="{% url 'make_order' %}" method="POST">
    {% csrf_token %}
    <div class="col-sm-4">
        {{ form.name|as_crispy_field }}
    </div>
    <div class="col-sm-4">
        {{ form.last_name|as_crispy_field }}
    </div>
    <div class="col-sm-4">
        {{ form.phone|as_crispy_field }}
    </div>
    {{ form.buying_type|as_crispy_field }}
    {{ form.address|as_crispy_field }}
    {{ form.date|as_crispy_field }}
    {{ form.comments|as_crispy_field }}

    <input type="submit" class="btn btn-success" value="Оформить заказ" style="margin-top: 24px; margin-bottom: 25px">
</form>

<script>
    $(document).ready(function () {
        $('#div_id_address').css('display', 'none')
        $('#id_buying_type').on('click', function () {
            buying_type = $(this).val()
            if(buying_type == 'delivery'){
                $('#div_id_address').css('display', 'block')
            }else{
                $('#div_id_address').css('display', 'none')
            }
        })
        $('#id_buying_type').css({'width': '150px', 'display':'inline'})
        $('#id_address').css({'width': '250px', 'display':'inline'})
        $('#id_date_day').css({'width': '50px', 'display':'inline'})
        $('#id_date_month').css({'width': '100px', 'display': 'inline'})
        $('#id_date_year').css({'width': '100px', 'display': 'inline'})
    })
</script>
{% endblock content %}

evmmarket/ecomapp/templates/thank_you.html
{% extends 'base.html' %}

{% block content %}

<div class="col-sm-8 col-sm-offset-2">
    <h3>Спасибо за ваш заказ. Он принят в обработку!</h3>
</div>
{% endblock content %}